# Generated by Django 4.2.5 on 2023-09-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('picture', models.ImageField(upload_to='images/')),
                ('show_until', models.DateTimeField()),
                ('show_since', models.DateTimeField()),
            ],
        ),
    ]
