# Generated by Django 4.2.5 on 2023-09-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('show_until', models.DateTimeField()),
                ('show_since', models.DateTimeField()),
                ('text', models.TextField(max_length=2000)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
